apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xs7dtyrhm-python
  janus-idp.io/tekton: xs7dtyrhm-python
  backstage.io/kubernetes-id: xs7dtyrhm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xs7dtyrhm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
